title: "Quantum4EnergyNL"
description: "Connecting quantum technologies and the energy transition in the Netherlands."
url: "https://ees-tue.github.io"   # weâ€™ll switch to your domain later
baseurl: "/quantum4energynl"       # required while testing under github.io

remote_theme: minima
